# autoscale with respect to memory utilization
  
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-ram-autoscale
spec:
  maxReplicas: 10
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-deployment # deployment name
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50