apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
  - protocol: TCP
    port: 31000
    targetPort: 31000 
    nodePort: 31000
  type: NodePort
