apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodeport: 4000
    type: NodePort