apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodeport: 5000
    type: NodePort